#!/bin/bash

HIGH_THRESHOLD=0.5
LOW_THRESHOLD=0.8
SIZE_THRESHOLD=20
MUL=true
TEST=false

if [ $# -lt 2 ]; then
	echo "Missing 2 Arguements" $# "providied"	 
	exit 1
elif [ $# -gt 3 ]; then
	echo "To many Arguements got" $#", expecting 2 or 3"
	exit 1
elif [ $# -eq 2 ]; then
	REPO_OWNER=$1
	REPO_NAME=$2
elif [ $# -eq 3 ]; then
	TEST=$3
	REPO_OWNER=$1
	REPO_NAME=$2
fi

# The directory where the log files will go
LOGDIR=../../parse_log/S${SIZE_THRESHOLD}\_L${LOW_THRESHOLD}\_H${HIGH_THRESHOLD}\_M${MUL}/

# The file that the log will be saved to. Format: O_R_t.t_mmddyyyy_HHMM
# O = Repo Owner, R = Repo name, t.t = high_threshold value (in decimal)
LOGFILE=${REPO_OWNER}\_${REPO_NAME}\_$(date +"%m%d%Y_%H%M")

# Full path of the file
FULLPATH=${LOGDIR}${LOGFILE}

# Make the directory if it doesnt already exist
mkdir -p $LOGDIR

ruby file_parser.rb ${REPO_OWNER} ${REPO_NAME} ${TEST} ${FULLPATH} ${MUL} ${HIGH_THRESHOLD} ${LOW_THRESHOLD} ${SIZE_THRESHOLD}

# Print on a new line after the progress bar
echo 

if [[ $? == 0 ]]; then
	echo file_parser.rb finished successfully
else
	echo file_parser.rb with exit code $RESULT
fi

echo log file: $FULLPATH
