#!/bin/bash

OUTPUT_DIR=../../../../heron-thesis/src/images

# should be the folder that contains the tests folders
# TARGET_FOLDER/test_1/svm/dagger/data.csv
#                                 times/
#                          acra
#                          ...
#                      rf/dagger/data.csv
#                                times/
#                                importance.csv
#                         acra
#                         ...
#               test_2
#               ...
TARGET_FOLDER=meaures/

command_location=../../../../heron-thesis/plots


CURRENT_DUR=`pwd`

echo "${CURRENT_DUR}"


if [ "$#" -eq 1 ]
then
    TARGET_FOLDER=$1
    #OUTPUT_DIR=$2
else
    echo "Invalid Arguements got" $#", expecting 1"
    exit 1
fi

for dir in "${TARGET_FOLDER}"*
do
    # is the file a directory?
    if [[ -f ${dir} ]]
    then
        continue
    fi

    # Get folder name
    test_name=$(basename "${dir}")


    # Iterate every method 
    for method in "${dir}"/*
    do

        # is the file a directory?
        if [[ -f ${method} ]]
        then
            continue
        fi

        method_name=$(basename "${method}")

        # Iterate every project 
        for project in "${method}"/*
        do
            # is the file a directory?
            if [[ -f ${project} ]]
            then
                continue
            fi

            if [[ ${method_name} = 'rf' ]]
            then
                project_name=$(basename "${project}")

                echo "${project}"
                cp "${project}/importance.csv" "${project}/importance.csv.bak"
                ruby importance_fixer.rb "${project}/importance.csv"
            fi
            
        done
    done
done

