#!/bin/bash

# The repo to be scraped and then parsed.
REPO_OWNER=nathanmarz
REPO_NAME=storm
THRESHOLD=1.0
TEST=false
MUL=true

# The directory where the log files will go
LOGDIR=../parse_log/${THRESHOLD}\_M${MUL}/

# The file that the log will be saved to. Format: O_R_t.t_mmddyyyy_HHMM
# O = Repo Owner, R = Repo name, t.t = threshold value (in decimal)
LOGFILE=${REPO_OWNER}\_${REPO_NAME}\_${THRESHOLD}\_$(date +"%m%d%Y_%H%M")

# Full path of the file
FULLPATH=${LOGDIR}${LOGFILE}

# Make the directory if it doesnt already exist
mkdir -p $LOGDIR

ruby file_parser.rb $REPO_OWNER $REPO_NAME $TEST $FULLPATH $THRESHOLD $MUL

if [[ $? == 0 ]]; then
	echo file_parser.rb finished successfully
else
	echo file_parser.rb with exit code $RESULT
fi

echo log file: $FULLPATH
